ministryofjustice/hmpps-digital-prison-reporting-mi

- .circleci/config.yml
- README.md
- helm_deploy/hmpps-digital-prison-reporting-mi/values.yaml
- helm_deploy/values-dev.yaml
- redshift-jdbc-secret.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/DigitalPrisonReportingMi.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/config/JdbcProperties.kt
- src/main/resources/application.yml
- Add JDBC credentials to new secret (manually deployed to env).
- Configured Helm to attach secrets as env vars.
- Configured Spring to use env vars as properties.
> [DPR-383] RedShift JDBC credentials

- .circleci/config.yml
- build.gradle.kts
- helm_deploy/hmpps-digital-prison-reporting-mi/values.yaml
- helm_deploy/values-dev.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/AuthAwareTokenConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/ResourceServerConfiguration.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/EstablishmentsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/TestResourceServerConfiguration.kt
Changes to call the HMPPS auth service to validate the token that was received from the frontend.
> Dpr 548 - Implementing HMPPS auth integration

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/config/DigitalPrisonReportingMiExceptionHandler.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/config/OpenApiConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/controller/EstablishmentController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/controller/ExternalMovementsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/model/Count.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/AuthAwareTokenConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/ResourceServerConfiguration.kt
- src/main/resources/application.yml
> [DPR-000] Swagger UI

- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/controller/ExternalMovementsController.kt
Updated swagger to clearly show what the value format for start and end date is.
> Updated swagger docs with startDate and endDate description, format and example values

- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/service/ConfiguredApiService.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/data/ConfiguredApiRepositoryTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ConfiguredApiIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/service/ConfiguredApiServiceTest.kt
This PR includes changes to return the json keys from the configured API as camelcase.
> DPR2-64 Make json keys camelcase

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/controller/ExternalMovementsController.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/AuthAwareTokenConverter.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/security/ResourceServerConfiguration.kt
- src/main/resources/application.yml
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/data/ExternalMovementRepositoryCustomTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ConfiguredApiIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ExternalMovementsIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/IntegrationTestBase.kt
- src/test/resources/application-test.yml
Imported the newest version of the library with the caseload functionality into the mi application to test the end to end integration. 
Note: Would the legacy external movement controllers also need to implement row level security? At the moment they do not.
> Dpr2 148 caseload integration tests

- build.gradle.kts
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/IntegrationTestBase.kt
This PR updates the reporting library version to latest and fixes the integration tests based on the new version changes.
> DPR2-177 updated lib to latest and fixed integration tests

- .trivyignore
- Dockerfile
- build.gradle.kts
- src/main/resources/application.yml
- src/main/resources/definitions.json
- src/main/resources/hospital-and-court-movements-1.0.3.json
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/data/ExternalMovementEntity.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ReportDefinitionIntegrationTest.kt
Updated the reporting mi host application to include hospital-and-court-movements-1.0.3.json and the latest version of the library.
> DPR2-221 update lib version and include hospital-and-court-movements-1.0.3.json file

- Dockerfile
- build.gradle.kts
- src/main/resources/application.yml
- src/main/resources/dpd001-court-hospital-movements.json
- src/main/resources/external-movements-1.0.0.json
- src/main/resources/external-movements.json
- src/main/resources/hospital-and-court-movements-1.0.3.json
Dpr2 268 update lib version to parse new policy structure in DPDs.
> Dpr2 268 update lib version to parse new dpd

- .circleci/config.yml
- Dockerfile
- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/resources/application.yml
- src/main/resources/dpd001-court-hospital-movements.json
- src/main/resources/external-movements.json
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ConfiguredApiIntegrationTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/IntegrationTestBase.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/ReportDefinitionIntegrationTest.kt
- src/test/resources/application-test.yml
Changes to configure the reporting mi application to call the definitions service.
- Removed the git submodule.
- Added the host name of the service to the application.yml
- Adapted integration tests to use wiremock
> DPR2-300 configure reporting mi application to use definitions web service

- build.gradle.kts
Updated reporting-mi to the latest library version to support access policy.
> DPR2-299 updated reporting-mi to the latest library version to support access policy

- build.gradle.kts
- src/main/resources/application.yml
Enabling cache for the reporting mi application.
> Dpr2 337 update lib version to include cache

- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/IntegrationTestBase.kt
This change is to redeploy main to Dev as currently a branch is deployed for testing purposes.
> DPR2-343 revert branch deployment to Dev

- build.gradle.kts
reporting-lib:3.0.0 -> reporting-lib:3.0.1
> bump version

- build.gradle.kts
> DPR2-413 updated lib version

- build.gradle.kts
- src/test/resources/dpd001-court-hospital-movements.json
- src/test/resources/external-movements.json
Updated lib to convert visible from boolean to enum.
> DPR2-413 updated lib version and amended DPDs

- build.gradle.kts
Updated lib to rename CTE stages.
> DPR2-427 updated lib version

- build.gradle.kts
Changes to include display dataset fallback.
> DPR2-267 updated lib version

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/AppInsightsConfig.kt
Added custom dimensions of username and activeCaseloadId to App Insights.
> Dpr2 269 app insights custom dim

- .circleci/config.yml
- build.gradle.kts
- helm_deploy/values-dev.yaml
- src/main/resources/application.yml
Updated library version and the rolearn with the new role for the Dev environment.
> Dpr2 758 update lib and rolearn

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/AthenaConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/RedshiftDataApiConf.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/RedshiftDataApiConfig.kt
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/StsCredentialsProviderConfig.kt
- Updated lib version.
- Removed ExecuteStatementRequest.Builder bean as it is now created inside RedshiftDataApiRepository in the library. 
- Added Athena configuration 
- Extracted the creation of the STS config in its own file.
> Update lib, remove requestBuilder, added Athena config and Sts refactoring

- build.gradle.kts
Updated lib to include Redshift async reports filters fix.
> DPR2-817 updated backend lib

- helm_deploy/values-test.yaml
This is in attempt to fix the auth issue we have in test for the async endpoints.
> DPR2-836 attempt to fix auth issue in test

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/resources/application.yml
- src/test/resources/application-test.yml
Make S3 location configurable per environment
> DPR2-836 make S3 location configurable per environment

- helm_deploy/values-preprod.yaml
Added preprod config for allowing to call the async APIs.
> DPR2-751 Added preprod config for async queries

- build.gradle.kts
Updated lib for datasource case-insensitive datasource name comparison.
> DPR2-790 Updated lib for datasource case-insensitive comparison.

- helm_deploy/values-prod.yaml
Added prod cross iam role config.
> DPR2-751 added prod cross iam role config

- build.gradle.kts
Library update to support filter queries from different datasets.
> DPR2-796 update library

- build.gradle.kts
Update library to convert DPD parameters to filters in the report definition response.
> DPR2-820 update library

- build.gradle.kts
Update library to support context_ CTE.
> DPR2-996 update library

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/resources/application.yml
This reverts commit 1f48ded44ecb81eef66b137b44a97105591f7566.
Reverted library version before the workgroup changes.
> Revert "DPR2-945 Athena workgroup config (#223)"

- build.gradle.kts
Update lib to hide prompt empty columns from reports.
> DPR2-1039 update lib

- build.gradle.kts
> no-jira update lib version

- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/AppInsightsConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/ClientTrackingInterceptorTest.kt
Changes on the reporting mi application to capture product name, variant name and page on App Insights.
> DPR2-1334 capture product name, variant name and page

- build.gradle.kts
Updated lib with the new dashboard definition changes.
This also removes the existing metrics endpoints.
> DPR2-1433 updated lib

- build.gradle.kts
Updated library to include all dashboard endpoints.
> DPR2-1391 updated lib

- .circleci/config.yml
- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/DynamoDbConfig.kt
Configure DynamoDB client to assume the cross-account role.
> Dpr2 1514 attempt to fix dynamo call

- build.gradle.kts
Update lib based on these changes:
https://github.com/ministryofjustice/hmpps-digital-prison-reporting-lib/pull/528
> no_jira update lib

- build.gradle.kts
- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
- helm_deploy/values-prod.yaml
- helm_deploy/values-test.yaml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/ResourceServerConfiguration.kt
> DPR2-1778 change host to call manage-users-api

- build.gradle.kts
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/AppInsightsConfig.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/ClientTrackingInterceptorTest.kt
- src/test/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/integration/IntegrationTestBase.kt
Upgraded BE library with latest changes which include updating the dashboard schema and the changes to allow the choice of using system tokens.
Note: We are still using a user token and have not yet migrated to system tokens.
> DPR2-1837 upgrade BE lib

- .circleci/config.yml
- src/main/kotlin/uk/gov/justice/digital/hmpps/digitalprisonreportingmi/configuration/RequestLoggerConfig.kt
With these changes the BE will log incoming HTTP requests which is very helpful when trying to investigate issues.
> DPR2-2166 Log Incoming requests

- build.gradle.kts
Reverts ministryofjustice/hmpps-digital-prison-reporting-mi#542
> Revert "revert 9.4.6"
